In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\flipkart_com-ecommerce.csv")
df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: bool(1), float64(2), object(12)
memory usage: 2.2+ MB

In [6]:
df.isnull().sum()

uniq_id                       0
crawl_timestamp               0
product_url                   0
product_name                  0
product_category_tree         0
pid                           0
retail_price                 78
discounted_price             78
image                         3
is_FK_Advantage_product       0
description                   2
product_rating                0
overall_rating                0
brand                      5864
product_specifications       14
dtype: int64

In [7]:
df.describe()

        retail_price  discounted_price
count   19922.000000      19922.000000
mean     2979.206104       1973.401767
std      9009.639341       7333.586040
min        35.000000         35.000000
25%       666.000000        350.000000
50%      1040.000000        550.000000
75%      1999.000000        999.000000
max    571230.000000     571230.000000

In [8]:
df = df.drop(columns=["uniq_id","crawl_timestamp","product_url","image"])

In [9]:
# handling missing values
df["brand"] = df["brand"].fillna("unknown")

In [10]:
## dropping rows where price in missing
df = df.dropna(subset=["retail_price","discounted_price"])

In [11]:
df.isnull().sum()

product_name                0
product_category_tree       0
pid                         0
retail_price                0
discounted_price            0
is_FK_Advantage_product     0
description                 2
product_rating              0
overall_rating              0
brand                       0
product_specifications     12
dtype: int64

In [12]:
df = df.drop(columns=["product_specifications"])

In [13]:
df = df.drop(columns=['description'])

In [14]:
df.isnull().sum()

product_name               0
product_category_tree      0
pid                        0
retail_price               0
discounted_price           0
is_FK_Advantage_product    0
product_rating             0
overall_rating             0
brand                      0
dtype: int64

In [15]:
df['category'] = df['product_category_tree'].str.replace('[\[\]"]', '', regex=True)

In [16]:
df['category'] = df['category'].str.split('>>').str[0].str.strip()

In [17]:
df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data/clean_flipkart.csv")

In [18]:
### feature 1 how much discount is given
df["discount_amount"] = df["retail_price"] - df["discounted_price"]
df.head()

,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,category,discount_amount
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,False,No rating available,No rating available,Alisha,Clothing,620.0
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,False,No rating available,No rating available,FabHomeDecor,Furniture,9511.0
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,False,No rating available,No rating available,AW,Footwear,500.0
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,No rating available,No rating available,Alisha,Clothing,432.0
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,False,No rating available,No rating available,Sicons,Pet Supplies,10.0

In [19]:
df.isnull().sum()

product_name               0
product_category_tree      0
pid                        0
retail_price               0
discounted_price           0
is_FK_Advantage_product    0
product_rating             0
overall_rating             0
brand                      0
category                   0
discount_amount            0
dtype: int64

In [20]:
## feature 2 discount percentage
df["discount_percent"] = (df["discount_amount"] / df["retail_price"]) * 100

In [21]:
df.head()

,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,category,discount_amount,discount_percent
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,False,No rating available,No rating available,Alisha,Clothing,620.0,62.062062
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,False,No rating available,No rating available,FabHomeDecor,Furniture,9511.0,29.576764
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,False,No rating available,No rating available,AW,Footwear,500.0,50.050050
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,No rating available,No rating available,Alisha,Clothing,432.0,61.802575
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,False,No rating available,No rating available,Sicons,Pet Supplies,10.0,4.545455

In [22]:
## feature 3 price category
def price_category(price):
    if price < 1000:
        return "low"
    elif price < 5000:
        return "medium"
    else:
        return "high"

df["price_category"] = df["discounted_price"].apply(price_category)

In [23]:
df.head()

,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,category,discount_amount,discount_percent,price_category
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,False,No rating available,No rating available,Alisha,Clothing,620.0,62.062062,low
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,False,No rating available,No rating available,FabHomeDecor,Furniture,9511.0,29.576764,high
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,False,No rating available,No rating available,AW,Footwear,500.0,50.050050,low
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,No rating available,No rating available,Alisha,Clothing,432.0,61.802575,low
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,False,No rating available,No rating available,Sicons,Pet Supplies,10.0,4.545455,low

In [24]:
df['product_rating'] = pd.to_numeric(df['product_rating'], errors='coerce')

In [25]:
## feature 4 rating category

def rating_category(rating):
    if rating >= 4:
        return 'Good'
    elif rating >= 2:
        return 'Average'
    else:
        return 'Poor'

df['rating_category'] = df['product_rating'].apply(rating_category)

In [26]:
df.head()

,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,category,discount_amount,discount_percent,price_category,rating_category
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,False,NaN,No rating available,Alisha,Clothing,620.0,62.062062,low,Poor
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,False,NaN,No rating available,FabHomeDecor,Furniture,9511.0,29.576764,high,Poor
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,False,NaN,No rating available,AW,Footwear,500.0,50.050050,low,Poor
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,NaN,No rating available,Alisha,Clothing,432.0,61.802575,low,Poor
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,False,NaN,No rating available,Sicons,Pet Supplies,10.0,4.545455,low,Poor

In [27]:

#spliting data 
products_df=df[["product_name","brand","category","product_rating"]]
pricing_df=df[["retail_price","discounted_price","discount_percent"]]

In [28]:
products_df.reset_index(inplace=True)
products_df.rename(columns={"index":"product_id"},inplace=True)

pricing_df["product_id"] = products_df["product_id"]

C:\Users\AKSHAT\AppData\Local\Temp\ipykernel_13564\2346312750.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_df.rename(columns={"index":"product_id"},inplace=True)
C:\Users\AKSHAT\AppData\Local\Temp\ipykernel_13564\2346312750.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pricing_df["product_id"] = products_df["product_id"]

In [29]:
products_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\products.csv",index=False)
pricing_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\pricing.csv",index=False)

In [30]:
products_df = products_df.drop(columns=['product_id'])

In [31]:
products_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\products.csv",index=False)
pricing_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\pricing.csv",index=False)

In [32]:
print(products_df.columns)

Index(['product_name', 'brand', 'category', 'product_rating'], dtype='object')

In [34]:
df['product_rating'].isnull().sum()

np.int64(18083)

In [35]:
df['product_rating'] = df['product_rating'].fillna(df['product_rating'].mean())

In [36]:
df['product_rating'].isnull().sum()

np.int64(0)

In [37]:
products_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\products.csv",index=False)
pricing_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\pricing.csv",index=False)

In [38]:
products_df.reset_index(drop=True, inplace=True)
products_df['product_id'] = products_df.index + 1

pricing_df['product_id'] = products_df['product_id']

C:\Users\AKSHAT\AppData\Local\Temp\ipykernel_13564\3916099776.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pricing_df['product_id'] = products_df['product_id']

In [39]:
products_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\products.csv",index=False)
pricing_df.to_csv(r"C:\Users\AKSHAT\Ecommerce-Analytics-Project\Data\pricing.csv",index=False)